apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
    - name: peer
      port: 2380
      targetPort: 2380
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: "etcd-headless"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.0
        command:
          - "/usr/local/bin/etcd"
          - "--initial-advertise-peer-urls=http://$(ETCD_NAME).etcd-headless:2380"
          - "--listen-peer-urls=http://0.0.0.0:2380"
          - "--advertise-client-urls=http://$(ETCD_NAME).etcd-headless:2379"
          - "--listen-client-urls=http://0.0.0.0:2379"
          - "--initial-cluster-token=etcd-cluster-1"
          - "--initial-cluster-state=new"
          - "--initial-cluster=etcd-0=http://etcd-0.etcd-headless:2380,etcd-1=http://etcd-1.etcd-headless:2380,etcd-2=http://etcd-2.etcd-headless:2380"
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
